### PR TITLE
ignore target/bin build folders

### PR DESCRIPTION
**Pull request by paulvi**

### CODE REVIEW

**Comment by dbickley** [comment]
Everything is merged in.  FYI this is my first open source project working with someone else. Please let me know if there is anything I can do to help, or if I am missing any obvious steps. Also, as I am sure you know, life sometimes gets busy. I apologize in advance if I am ever slow to respond.

**Comment by paulvi** [comment]
Just be yourself, all open source differs

**Comment by dbickley** [comment]
Thanks :)

FYI I am planning on uploading the two parallel projects needed to build
the "feature" that gets added to the "site".  Maybe tonight, hopefully
tomorrow, probably sometime this weekend :)

**Comment by paulvi** [comment]
OK, see https://github.com/dbickley/OpenEditors/issues/17#issuecomment-387592048

It should be within this project (so build is possible right after `git clone`).
That also enable CI servers like https://travis-ci.org/

**Pull request merged**
